# Generated by Django 4.2.1 on 2023-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(default='No image available', upload_to='photos/brand')),
                ('caption', models.TextField(max_length=200)),
            ],
        ),
    ]
