# Generated by Django 4.2.1 on 2023-08-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ban',
        ),
    ]
