# Generated by Django 4.2.1 on 2023-08-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_od_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_status', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Orderstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='od_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.orderstatus'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderitem_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.itemstatus'),
        ),
    ]
