# Generated by Django 4.2.1 on 2023-08-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_itemstatus_orderstatus_remove_order_od_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default='Pending', null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.orderstatus'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_status',
            field=models.ForeignKey(default='Pending', null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.itemstatus'),
        ),
    ]
