# Generated by Django 4.2.1 on 2023-08-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
