# Generated by Django 4.2.1 on 2023-08-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_return_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_total_price',
            field=models.IntegerField(null=True),
        ),
    ]
