# Generated by Django 4.2.1 on 2023-08-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
