# Generated by Django 4.2.1 on 2023-08-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_banner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_name',
        ),
    ]
