# Generated by Django 4.2.2 on 2023-07-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_range',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_range',
            field=models.CharField(max_length=60),
        ),
    ]
